on:
  workflow_dispatch:
  pull_request:
    branches:
      - staging
    types: [closed]

jobs:
  attach_label:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Attach Label
        id: hello
        uses: Aivyss/github-action-test2@v1.8.3
        with:
          github_token: ${{ secrets.TOKEN_TEST }}
          label: staging
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"