on:
  workflow_dispatch:
  pull_request:
    branches:
      - dummy2
    types: [closed]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: milestone labeling
    steps:
      - name: milestone labeling
        id: hello
        uses: Aivyss/milestone-labeler@v1.0.0
        with:
          github_token: ${{ secrets.TOKEN_TEST }}
          label: 'staging'
          per_page: 50