name: Merge to milestone branch

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  merge_milestone:
    name: merge-milestone
    environment: milestone
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.TOKEN_TEST }}
          source: 'main'
          target: 'milestone'
          webhook_url:
      - name: Get Pull Request Number
        id: pr
        run: echo "pull_request_number=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_TEST }}
      - run: echo ${{ steps.pr.outputs.pull_request_number }}
      - name: attach label
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.TOKEN_TEST }}"
          pr-number: "${{ steps.pr.outputs.pull_request_number }} "
  merge_staging:
    name: merge-staging
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.TOKEN_TEST }}
          source: 'main'
          target: 'staging'
          webhook_url: