name: Merge to milestone branch

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]
env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  merge_milestone:
    name: merge-milestone
    environment: milestone
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.TOKEN_TEST }}
          source: 'main'
          target: 'milestone'
          webhook_url:
      - name: attach label
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.TOKEN_TEST }}"
  merge_staging:
    name: merge-staging
    environment: staging
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.TOKEN_TEST }}
          source: 'main'
          target: 'staging'
          webhook_url:
      - name: attach label
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.TOKEN_TEST }}"